"""empty message

Revision ID: 21e8b3ccae65
Revises: None
Create Date: 2016-12-12 23:33:45.758813

"""

# revision identifiers, used by Alembic.
revision = '21e8b3ccae65'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1', sa.Text(), nullable=True),
    sa.Column('player2', sa.Text(), nullable=True),
    sa.Column('game_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    ### end Alembic commands ###
